import { Inter } from "next/font/google";

import "./globals.css";
import Layouts from "@/components/Layouts/Layouts"; 

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "The Foodie cafe",
  description: "Generated by create next app",
};


export default function RootLayout({children}) {
  return (
    <html lang="en" className={`${inter.className} `}>
      <body>
        <Layouts>
          {children}
        </Layouts>
      </body>
    </html>
  );
}