import { ThemeProvider } from "next-themes";
import "./globals.css";
import Layouts from "@/components/Layouts/Layouts"; 
import { CartProvider } from "@/utils/ContextReducer";


export const metadata = {
  title: "The Foodie cafe",
  description: "Generated by create next app",
};


export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
          <CartProvider>
            <Layouts>
              {children}
            </Layouts>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}